// <auto-generated />
using System;
using Intranet.Api.MultifamilyLbp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Intranet.Api.MultifamilyLbp.Data.Migrations
{
    [DbContext(typeof(MultifamilyDbContext))]
    [Migration("20260528195323_InitialMultifamily")]
    partial class InitialMultifamily
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Intranet.Api.MultifamilyLbp.Data.Entities.InspectionRowRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Condition")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPositive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("JobEntityId")
                        .HasColumnType("uuid");

                    b.Property<double>("LeadContent")
                        .HasColumnType("double precision");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Multifamily")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedComponent")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedSubstrate")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("ReadingId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoomNumber")
                        .HasColumnType("text");

                    b.Property<string>("RoomOrArea")
                        .HasColumnType("text");

                    b.Property<string>("RoomType")
                        .HasColumnType("text");

                    b.Property<int>("ShotCount")
                        .HasColumnType("integer");

                    b.Property<string>("Side")
                        .HasColumnType("text");

                    b.Property<string>("SiteAddress")
                        .HasColumnType("text");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Substrate")
                        .HasColumnType("text");

                    b.Property<string>("Timestamp")
                        .HasColumnType("text");

                    b.Property<string>("UnitNumber")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UploadBatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JobEntityId");

                    b.HasIndex("UploadBatchId");

                    b.HasIndex("JobEntityId", "ReadingId");

                    b.ToTable("InspectionRows");
                });

            modelBuilder.Entity("Intranet.Api.MultifamilyLbp.Data.Entities.JobEntityRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntitySlug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "EntitySlug")
                        .IsUnique();

                    b.ToTable("JobEntities");
                });

            modelBuilder.Entity("Intranet.Api.MultifamilyLbp.Data.Entities.JobRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FacilityAddress")
                        .HasColumnType("text");

                    b.Property<string>("FacilityName")
                        .HasColumnType("text");

                    b.Property<string>("JobIdentifier")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("JobStatus")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("JobIdentifier")
                        .IsUnique();

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Intranet.Api.MultifamilyLbp.Data.Entities.NormalizationCacheRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FieldName", "OriginalValue")
                        .IsUnique();

                    b.ToTable("NormalizationCaches");
                });

            modelBuilder.Entity("Intranet.Api.MultifamilyLbp.Data.Entities.NormalizationSuggestionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AffectedRowCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text");

                    b.Property<string>("ApprovedValue")
                        .HasColumnType("text");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("JobEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("OriginalValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SuggestedValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("JobEntityId", "FieldName", "OriginalValue");

                    b.ToTable("NormalizationSuggestions");
                });

            modelBuilder.Entity("Intranet.Api.MultifamilyLbp.Data.Entities.ReportSnapshotRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeneratedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("JobEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("UniformThreshold")
                        .HasColumnType("double precision");

                    b.Property<bool>("UseNormalizedValues")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("JobEntityId");

                    b.ToTable("ReportSnapshots");
                });

            modelBuilder.Entity("Intranet.Api.MultifamilyLbp.Data.Entities.UploadBatchRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BatchName")
                        .HasColumnType("text");

                    b.Property<string>("BuildingProperty")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorLogJson")
                        .HasColumnType("text");

                    b.Property<int>("ImportedRowCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("InspectionDate")
                        .HasColumnType("date");

                    b.Property<Guid>("JobEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("SharePointFileUrl")
                        .HasColumnType("text");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValidationWarningsJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JobEntityId");

                    b.ToTable("UploadBatches");
                });

            modelBuilder.Entity("Intranet.Api.MultifamilyLbp.Data.Entities.InspectionRowRecord", b =>
                {
                    b.HasOne("Intranet.Api.MultifamilyLbp.Data.Entities.JobEntityRecord", "JobEntity")
                        .WithMany("InspectionRows")
                        .HasForeignKey("JobEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Intranet.Api.MultifamilyLbp.Data.Entities.UploadBatchRecord", "UploadBatch")
                        .WithMany("InspectionRows")
                        .HasForeignKey("UploadBatchId");

                    b.Navigation("JobEntity");

                    b.Navigation("UploadBatch");
                });

            modelBuilder.Entity("Intranet.Api.MultifamilyLbp.Data.Entities.JobEntityRecord", b =>
                {
                    b.HasOne("Intranet.Api.MultifamilyLbp.Data.Entities.JobRecord", "Job")
                        .WithMany("Entities")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Intranet.Api.MultifamilyLbp.Data.Entities.NormalizationSuggestionRecord", b =>
                {
                    b.HasOne("Intranet.Api.MultifamilyLbp.Data.Entities.JobEntityRecord", "JobEntity")
                        .WithMany("NormalizationSuggestions")
                        .HasForeignKey("JobEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobEntity");
                });

            modelBuilder.Entity("Intranet.Api.MultifamilyLbp.Data.Entities.ReportSnapshotRecord", b =>
                {
                    b.HasOne("Intranet.Api.MultifamilyLbp.Data.Entities.JobEntityRecord", "JobEntity")
                        .WithMany("ReportSnapshots")
                        .HasForeignKey("JobEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobEntity");
                });

            modelBuilder.Entity("Intranet.Api.MultifamilyLbp.Data.Entities.UploadBatchRecord", b =>
                {
                    b.HasOne("Intranet.Api.MultifamilyLbp.Data.Entities.JobEntityRecord", "JobEntity")
                        .WithMany("UploadBatches")
                        .HasForeignKey("JobEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobEntity");
                });

            modelBuilder.Entity("Intranet.Api.MultifamilyLbp.Data.Entities.JobEntityRecord", b =>
                {
                    b.Navigation("InspectionRows");

                    b.Navigation("NormalizationSuggestions");

                    b.Navigation("ReportSnapshots");

                    b.Navigation("UploadBatches");
                });

            modelBuilder.Entity("Intranet.Api.MultifamilyLbp.Data.Entities.JobRecord", b =>
                {
                    b.Navigation("Entities");
                });

            modelBuilder.Entity("Intranet.Api.MultifamilyLbp.Data.Entities.UploadBatchRecord", b =>
                {
                    b.Navigation("InspectionRows");
                });
#pragma warning restore 612, 618
        }
    }
}
